<?php
/**
 * Monitors user login to persist WooCommerce session ID in InPost Pay cart session.
 *
 * @since 2.0.5.3
 * @author Ilabs
 * @package Inpost_Pay\hooks
 */

namespace Ilabs\Inpost_Pay\hooks;

use Ilabs\Inpost_Pay\EntityLayer\Repository\BasketBindingRepository;
use Ilabs\Inpost_Pay\Lib\Basket\BasketPutService;
use Ilabs\Inpost_Pay\Lib\BasketIdentification;
use Ilabs\Inpost_Pay\Lib\helpers\DigitalProduct;
use Ilabs\Inpost_Pay\Lib\InPostIzi;
use Ilabs\Inpost_Pay\Models\CartSessionService;
use Ilabs\Inpost_Pay\WooCommerce\WooCommerceInPostIzi;
use function Ilabs\Inpost_Pay\inpost_pay_container;

/**
 * Handles login event to persist WooCommerce session ID in InPost Pay cart session.
 */
class LogInMonitor extends Base {
	/**
	 * Register WordPress hook for login event.
	 *
	 * @since 2.0.5.3
	 * @return void
	 */
	public function attach_hook(): void {
		add_action( 'woocommerce_guest_session_to_user_id', array( $this, 'log_in' ), 10, 2 );
	}

	/**
	 * Persist WooCommerce session ID to the InPost Pay cart session when user logs in.
	 *
	 * @param string $guest_session_id The former session ID, as generated by `::generate_customer_id()`.
	 * @param string $user_session_id The Customer ID that the former session was converted to.
	 * @return void
	 */
	public function log_in( string $guest_session_id, string $user_session_id ): void {
		if ( $guest_session_id === $user_session_id ) {
			return;
		}

		add_action(
			'woocommerce_init',
			static function () use ( $user_session_id ) {

				if ( ! isset( $_COOKIE['basket_binding_api_key'] ) ) {
					return;
				}

				/**
				 * Get from container DI.
				 *
				 * @var BasketBindingRepository $basket_binding_repository
				 */
				$basket_binding_repository = inpost_pay_container()->get( BasketBindingRepository::SERVICE_KEY );

				$basket_bind = $basket_binding_repository->find_by_api_key( sanitize_text_field( wp_unslash( $_COOKIE['basket_binding_api_key'] ) ) );
				if ( null === $basket_bind ) {
					return;
				}
				$cart_id = $basket_bind->get_basket_id();
				if ( null === $cart_id ) {
					return;
				}

				BasketIdentification::set( $cart_id );

				/**
				 * Get from container DI.
				 *
				 * @var CartSessionService $cart_session
				 */
				$cart_session = inpost_pay_container()->get( CartSessionService::SERVICE_KEY );

				$session_entity = $cart_session->get_entity_by_cart_id( $cart_id );

				if ( null === $session_entity ) {
					return;
				}

				if ( $session_entity->get_wc_cart_session() === $user_session_id ) {
					return;
				}

				$session_entity->set_wc_cart_session( $user_session_id );
				add_action(
					'shutdown',
					static function () {
						$izi = WooCommerceInPostIzi::get_instance();
						DigitalProduct::handleDigitalProduct();
						/**
						 * Get from container DI.
						 *
						 * @var BasketPutService $basket_put_service
						 */
						$basket_put_service = inpost_pay_container()->get( BasketPutService::SERVICE_KEY );
						$basket_put_service->put(
							fn() => $izi->getBasket(),
							$izi->get_controller()
						);
					},
					PHP_INT_MAX - 1
				);
			}
		);
	}
}
